# Generated by Django 3.1.14 on 2022-08-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_idea_skills'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='ideas',
            field=models.ManyToManyField(blank=True, to='idea.Idea'),
        ),
    ]
