version: "3.9"
services:
  web:
    build: ./app
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/code
    ports:
    - 8000:8000
    env_file:
      - ./.env

#volumes:
  #postgres_data:
