# Generated by Django 3.2.14 on 2022-07-22 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_comment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ('title',), 'verbose_name': 'ایده', 'verbose_name_plural': 'ایده ها '},
        ),
        migrations.AddField(
            model_name='idea',
            name='comments',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='idea_comments', to='idea.comment'),
        ),
    ]
