# Generated by Django 3.2.14 on 2022-07-22 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_auto_20220722_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='comments',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_comments', to='idea.comment'),
        ),
    ]
