# Generated by Django 3.2.14 on 2022-07-22 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea', '0005_alter_idea_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_comments', to='idea.comment'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='idea_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
