# Generated by Django 3.2.14 on 2022-07-22 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0007_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='likes',
        ),
        migrations.AddField(
            model_name='idea',
            name='likes',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='idea_likes', to='idea.like'),
            preserve_default=False,
        ),
    ]
