# Generated by Django 3.2.14 on 2022-07-31 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0010_alter_idea_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_likes', to='idea.like'),
        ),
    ]
